# SITE CONFIGURATION
title: "Armno"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://armno.github.io" # the base hostname & protocol for your site
exclude: ["sass", "archived", "node_modules", "gulpfile.js", "package.json", "Rakefile"]
permalink: /:year/:month/:day/:title

paginate: 7

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
