# SITE CONFIGURATION
title: "Armno"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://armno.in.th"
exclude: ["sass", "archived", "node_modules", "gulpfile.js", "package.json", "Rakefile"]
permalink: pretty

paginate: 10

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

gems:
  - jekyll-feed
  - jekyll-paginate
